import type { RefObject } from 'react';
import type { AiEducationalFeedback } from '../types/aiFeedback';

interface DashboardAiFeedbackProps {
  feedback: AiEducationalFeedback;
  headingRef?: RefObject<HTMLHeadingElement | null>;
}

// Renders validated Gemini output as plain React text — never raw HTML.
function DashboardAiFeedback({ feedback, headingRef }: DashboardAiFeedbackProps) {
  const listSections = [
    { key: 'strengths', title: 'Recurring Strengths', items: feedback.strengths },
    { key: 'areas', title: 'Areas to Review', items: feedback.areasToReview },
    { key: 'steps', title: 'Suggested Next Steps', items: feedback.nextSteps },
  ].filter((section) => section.items.length > 0);

  return (
    <div className="dashboard-ai-result">
      <div className="dashboard-ai-result-header">
        <h3 className="dashboard-ai-overview-title" tabIndex={-1} ref={headingRef}>
          Feedback Overview
        </h3>
        <span className="dashboard-ai-generated-label">
          Generated by Gemini · Optional explanation
        </span>
      </div>

      <p className="dashboard-ai-overview">{feedback.overview}</p>

      {listSections.length > 0 && (
        <div className="dashboard-ai-content-grid">
          {listSections.map((section) => (
            <div key={section.key} className="dashboard-ai-content-section">
              <h4 className="dashboard-ai-content-title">{section.title}</h4>
              <ul className="dashboard-ai-list">
                {section.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      <p className="dashboard-ai-disclaimer">
        <strong>Educational Disclaimer:</strong> {feedback.disclaimer}
      </p>
    </div>
  );
}

export default DashboardAiFeedback;
